# Generated by Django 5.0.1 on 2024-01-10 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paramaters', '0001_initial'),
        ('trailers', '0005_trailer_serial_number_alter_trailer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electricmeter',
            name='trailer',
        ),
        migrations.AlterField(
            model_name='electricmeter',
            name='serial_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trailer_serial_number', to='trailers.trailer', verbose_name='Seri Numarasi'),
        ),
    ]
