# Generated by Django 5.0.1 on 2024-01-10 13:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paramaters', '0002_remove_electricmeter_trailer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricmeter',
            name='last_t0',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12, null=True, verbose_name='Onceki T0'),
        ),
    ]
