# Generated by Django 5.0.1 on 2024-01-10 14:02

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paramaters', '0003_electricmeter_last_t0'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electricmeter',
            name='created_at',
        ),
        migrations.AddField(
            model_name='electricmeter',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Tarih'),
        ),
        migrations.AddField(
            model_name='electricmeter',
            name='last_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Onceki Tarih'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='electricmeter',
            name='last_t1',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12, null=True, verbose_name='Onceki T1'),
        ),
        migrations.AddField(
            model_name='electricmeter',
            name='last_t2',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12, null=True, verbose_name='Onceki T2'),
        ),
        migrations.AddField(
            model_name='electricmeter',
            name='last_t3',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12, null=True, verbose_name='Onceki T3'),
        ),
    ]
