# Generated by Django 5.0.1 on 2024-01-10 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paramaters', '0004_remove_electricmeter_created_at_electricmeter_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ElectricMeter',
        ),
    ]
