# Generated by Django 5.0.1 on 2024-01-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paramaters', '0005_delete_electricmeter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='price',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Son Guncelleme Tarihi'),
        ),
    ]
