# Generated by Django 5.0.1 on 2024-01-09 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trailers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CandidateUserComment',
            new_name='Trailer',
        ),
    ]
