# Generated by Django 5.0.1 on 2024-01-09 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trailers', '0002_rename_candidateusercomment_trailer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trailer',
            old_name='username',
            new_name='name',
        ),
    ]
