# Generated by Django 5.0.1 on 2024-01-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trailers', '0004_alter_trailer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailer',
            name='serial_number',
            field=models.CharField(max_length=15, null=True, verbose_name='Sayac Seri Numarasi'),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='name',
            field=models.CharField(max_length=40, null=True, verbose_name='Karavan Ismi'),
        ),
    ]
