# Generated by Django 5.0.1 on 2024-01-10 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trailers', '0005_trailer_serial_number_alter_trailer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trailer',
            name='name',
        ),
    ]
