# Generated by Django 5.0.1 on 2024-01-10 14:48

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trailers', '0006_remove_trailer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trailer',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='trailer',
            name='is_active',
        ),
        migrations.AddField(
            model_name='trailer',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Tarih'),
        ),
        migrations.AddField(
            model_name='trailer',
            name='last_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Onceki Tarih'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trailer',
            name='last_rc',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12, null=True, verbose_name='Onceki RC'),
        ),
        migrations.AddField(
            model_name='trailer',
            name='last_ri',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12, null=True, verbose_name='Onceki RI'),
        ),
        migrations.AddField(
            model_name='trailer',
            name='last_t0',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12, null=True, verbose_name='Onceki T0'),
        ),
        migrations.AddField(
            model_name='trailer',
            name='last_t1',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12, null=True, verbose_name='Onceki T1'),
        ),
        migrations.AddField(
            model_name='trailer',
            name='last_t2',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12, null=True, verbose_name='Onceki T2'),
        ),
        migrations.AddField(
            model_name='trailer',
            name='last_t3',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12, null=True, verbose_name='Onceki T3'),
        ),
        migrations.AddField(
            model_name='trailer',
            name='price',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=15, null=True, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='trailer',
            name='rc',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12, null=True, verbose_name='RC'),
        ),
        migrations.AddField(
            model_name='trailer',
            name='ri',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12, null=True, verbose_name='RI'),
        ),
        migrations.AddField(
            model_name='trailer',
            name='t0',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12, null=True, verbose_name='T0'),
        ),
        migrations.AddField(
            model_name='trailer',
            name='t1',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12, null=True, verbose_name='T1'),
        ),
        migrations.AddField(
            model_name='trailer',
            name='t2',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12, null=True, verbose_name='T2'),
        ),
        migrations.AddField(
            model_name='trailer',
            name='t3',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12, null=True, verbose_name='T3'),
        ),
    ]
