# Generated by Django 5.0.1 on 2024-01-10 19:25

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trailers', '0008_alter_trailer_last_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Eklenme Tarihi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trailer',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 10, 22, 25, 6, 779116), verbose_name='Onceki Tarih'),
        ),
    ]
