# Generated by Django 5.0.1 on 2024-01-10 19:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trailers', '0009_trailer_created_at_alter_trailer_last_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trailer',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='trailer',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 10, 22, 49, 29, 676233), verbose_name='Onceki Tarih'),
        ),
    ]
