# Generated by Django 5.0.1 on 2024-01-11 12:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trailers', '0010_remove_trailer_created_at_alter_trailer_last_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailer',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 11, 15, 13, 10, 351097), verbose_name='Onceki Tarih'),
        ),
    ]
